trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  - name: System.Debug
    value: true

stages:
- stage: BuildApp
  displayName: Build Apps
  jobs:
  - job: BuildFrontendApp
    displayName: Build Frontend App
    steps:
    - script: echo building frontend app
      displayName: build frontend app
  - job: DeploytoUat
    displayName: Build Backend App
    steps:
    - script: echo building backend app
      displayName: build backend app
    - script: echo running unit tests for backend app
      displayName: unit tests backend

- stage: DeploytoDev
  dependsOn: []
  displayName: Deploy to DEV environment
  jobs:
  - job: DeployFrontendDev
    displayName: Deploy frontend to DEV
    steps:
    - script: echo deploying frontend app to DEV
      displayName: deploy frontend app to DEV

  - job: DeployBackendDev
    displayName: Deploy backend to DEV
    steps:
    - script: echo deploying backend app to DEV
      displayName: deploy backend app to DEV

- stage: DeployProd
  dependsOn: []
  displayName: Deploy to PROD environment
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: DeployFrontendProd
    displayName: Deploy frontend to PROD
    steps:
    - script: echo deploying frontend app to PROD
      displayName: deploy frontend app to PROD

  - job: DeployBackendProd
    displayName: Deploy backend to PROD
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo deploying backend app to PROD
      displayName: deploy backend app to PROD
